# see https://clang.llvm.org/docs/ClangFormatStyleOptions.html
---
BasedOnStyle: LLVM
Language: Cpp
Standard: Cpp14

ColumnLimit: 100

AccessModifierOffset: -4
IndentWidth: 4
UseTab: Never
LineEnding: LF

AlignEscapedNewlines: Left
AllowShortFunctionsOnASingleLine: Empty
AllowShortLambdasOnASingleLine: Empty
AlwaysBreakTemplateDeclarations: true
BreakConstructorInitializers: BeforeComma
IndentPPDirectives: AfterHash
PointerAlignment: Left
